spring.application.name=turf-backend

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/turfdb1}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:changeme}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
